# Generated by Django 5.0 on 2024-05-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='is_selling',
            field=models.BooleanField(default=False),
        ),
    ]
